version: "3"
services:
  kong:
    build:
      context: .
      dockerfile: "Dockerfile"
    image: "mrsaints/kong-dev"
    command: ["kong", "start", "-v"]
    entrypoint: /kong-entrypoint.sh
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=postgres
      # Disable daemon mode so the container won't exit immediately
      # - KONG_NGINX_DAEMON=off
    volumes:
      - ./conf/kong-entrypoint.sh:/kong-entrypoint.sh
      # Mount local Kong repository
      # - ./kong/:/kong/
      # Mount custom plugin
      # - ./kong-plugin/:/kong-plugin/
    ports:
      - "7946:7946"
      - "8000:8000"
      - "8001:8001"
      - "8443:8443"
      - "8444:8444"
    links:
      - postgres
    network_mode: "bridge"

  postgres:
    image: "postgres:9.4"
    environment:
      - POSTGRES_USER=kong
      - POSTGRES_DB=kong
    volumes:
      - ./conf/init-test-db.sh:/docker-entrypoint-initdb.d/init-test-db.sh:ro
    ports:
      - "5432:5432"
    network_mode: "bridge"
